filter queue by any field
sindresorhus/p-queue pull request #156
Opened 2021-09-15 07:22 UTC by slavb18

queue.sizeBy currently supports filtering by priority only
it could be extended to any prop
e.g.
```javascript
const options = { uid: '341a0c1b-147a-4b8e-9b9d-186773918a25' };
queue.add(() => delay(2000), options);
console.log('size by', queue.sizeBy({ uid: '341a0c1b-147a-4b8e-9b9d-186773918a25' }));
```

2021-09-15 07:33 UTC, sindresorhus requested changes

2021-09-15 07:33 UTC, sindresorhus commented on source/shallow-equal.ts
> +	for (const key of keys1) {
Use `Object.entries`. It can also just be inline here.

2021-09-15 07:33 UTC, sindresorhus commented on source/shallow-equal.ts
> +export function shallowPartialEqual(object1: any, object2: any) {
```suggestion
export function shallowPartialEqual(object1: object, object2: object) {
```

2021-09-15 07:33 UTC, sindresorhus commented on source/priority-queue.ts
> +			...options,
I don't think it should be able to overwrite `run`.

2021-09-15 07:34 UTC, sindresorhus commented
Can you add a test and docs updates?

2022-01-01 20:22 UTC, sindresorhus requested changes

2022-01-01 20:22 UTC, sindresorhus commented on test/test.ts
>  test('.add() - timeout without throwing', async t => {
```suggestion
});

test('.add() - timeout without throwing', async t => {
```

2022-01-01 20:22 UTC, sindresorhus commented on readme.md
> +You can pass any keys in options to use then later in sizeBy filtering
There should rather be a description under `#### options`, that you can pass any other key.

2022-01-01 20:22 UTC, sindresorhus commented on readme.md
> +You can pass any keys in options to use then later in sizeBy filtering
```suggestion
##### any other key

Type: `object`

You can pass any keys in options to use then later in `sizeBy` filtering.
```

Also this sentence doesn't read well.

2022-02-01 05:19 UTC, sindresorhus commented
Bump :)

2022-02-13 11:22 UTC, sindresorhus commented
Tests are not passing.

2022-02-13 11:38 UTC, Richienb requested changes
The types need to be updated

2022-02-13 11:38 UTC, Richienb commented on readme.md
> +You can pass any keys in options to use then later in `sizeBy` filtering.
There should be an extra newline after this

2022-02-13 11:38 UTC, Richienb commented on source/shallow-equal.ts
> +	for (const [key, value] of Object.entries(object1)) {
This could be done in one line with `.every()`

2022-02-13 11:38 UTC, Richienb commented on test/test.ts
> +	t.is(queue.sizeBy({uid: '07227c1e-0476-46b5-bd5b-5436626ede16'}), 0);
A simpler id system should be used to make it easier to test. Maybe something like `{id: 'foo'}`.

2022-02-13 11:38 UTC, Richienb commented on readme.md
> +For example, this can be used to find the number of items remaining in the queue with a specific priority level or any other field.
There should be a detailed example given instead of just `any other field`.

2022-02-13 11:40 UTC, Richienb commented on readme.md
> +You can pass any keys in options to use then later in `sizeBy` filtering.
Should be reworded to make it more direct

2022-03-08 09:13 UTC, Richienb commented
Bump :)

2022-04-06 14:36 UTC, closed without merging